- name: Install system packages 1
  become: true
  apt:
    name:
      - build-essential
      - cmake
      - pkg-config
      - libpthread-stubs0-dev
      - unzip
      - libtool
      - libtool-bin
      - gettext
      - curl
      - htop
      - git
      - software-properties-common
      - npm
  tags:
    - install
    - base

- name: Create home directory structure
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
    mode: '0755' 
  with_items:
    - workspace
  tags:
    - install
    - base

- name: Set bash to vi-mode
  lineinfile:
    - dest: "{{ lookup('env', 'HOME')/.bash_profile"
      line: set -o vi && bind '"jk":vi-movement-mode'
      state: present
