- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
    - install
    - rust

- name: Remove previous build directory if exists
  when: cargo_exists is failed
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/tmp_build/sh.rustup.rs"
    state: absent
  tags:
    - install
    - rust

- name: Download rustup
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: "{{ lookup('env', 'HOME') }}/tmp_build/sh.rustup.rs"
    mode: '0755'
    force: 'yes'
  tags:
    - install
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: "{{ lookup('env', 'HOME') }}/tmp_build/sh.rustup.rs -y"
  tags:
    - install
    - rust

- name: Delete tmp build directory
  when: cargo_exists is failed
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/tmp_build"
    state: absent
  tags:
    - install
    - rust

- name: Install rust stable version
  command: rustup toolchain install stable
  tags:
    - install
    - rust

- name: Install rust nightly version
  command: rustup toolchain install nightly
  tags:
    - install
    - rust

- name: Setup default rust version to stable
  command: rustup default stable
  tags:
    - install
    - rust
